// Curated catalog of real, well-known scholarships. Update by PR.
// Originally ported from the ADA final-project week_7 dataset.

export type CatalogScholarship = {
  id: string;
  title: string;
  source: "curated";
  url: string;
  amount: number | null;
  deadline: string | null; // ISO date "YYYY-MM-DD" or null for rolling
  eligibilityTags: string[];
  requirements: string[];
  estimatedEffort: 1 | 2 | 3 | 4 | 5;
  description: string;
};

export const SCHOLARSHIP_CATALOG: CatalogScholarship[] = [
  {
    id: "curated:001",
    title: "Fulbright U.S. Student Program",
    source: "curated",
    url: "https://us.fulbrightonline.org/",
    amount: null,
    deadline: "2026-10-13",
    eligibilityTags: ["graduate", "undergraduate", "research", "international"],
    requirements: ["essay", "statement-of-grant-purpose", "three-letters", "transcript", "language-evaluation"],
    estimatedEffort: 5,
    description: "Fully-funded grant for U.S. citizens to study, research, or teach English abroad for one academic year. Award covers travel, living, and project costs.",
  },
  {
    id: "curated:002",
    title: "Gates Scholarship",
    source: "curated",
    url: "https://www.thegatesscholarship.org/",
    amount: null,
    deadline: "2026-09-15",
    eligibilityTags: ["undergraduate", "need-based", "minority", "high-school-senior"],
    requirements: ["essay", "transcript", "two-letters", "fafsa"],
    estimatedEffort: 4,
    description: "Last-dollar scholarship for outstanding minority high school seniors with significant financial need. Covers full cost of attendance not met by other aid.",
  },
  {
    id: "curated:003",
    title: "Coca-Cola Scholars Program",
    source: "curated",
    url: "https://www.coca-colascholarsfoundation.org/",
    amount: 20000,
    deadline: "2026-10-31",
    eligibilityTags: ["undergraduate", "high-school-senior", "leadership", "community-service"],
    requirements: ["essay", "transcript", "leadership-statement"],
    estimatedEffort: 4,
    description: "Achievement-based scholarship awarded to 150 high school seniors each year demonstrating leadership, academic excellence, and community service.",
  },
  {
    id: "curated:004",
    title: "Jack Kent Cooke Undergraduate Transfer Scholarship",
    source: "curated",
    url: "https://www.jkcf.org/our-scholarships/undergraduate-transfer-scholarship/",
    amount: 55000,
    deadline: "2026-11-09",
    eligibilityTags: ["undergraduate", "transfer", "community-college", "need-based", "merit-based"],
    requirements: ["essay", "transcript", "two-letters", "financial-documentation"],
    estimatedEffort: 5,
    description: "For high-achieving community college students with financial need transferring to four-year institutions. Up to $55,000 per year.",
  },
  {
    id: "curated:005",
    title: "Hispanic Scholarship Fund General Scholarship",
    source: "curated",
    url: "https://www.hsf.net/scholarship",
    amount: 5000,
    deadline: "2027-02-15",
    eligibilityTags: ["hispanic", "undergraduate", "graduate", "merit-based"],
    requirements: ["essay", "transcript", "fafsa"],
    estimatedEffort: 3,
    description: "Awards $500 to $5,000 to students of Hispanic heritage pursuing higher education. Renewable based on continued academic performance.",
  },
  {
    id: "curated:006",
    title: "Dell Scholars Program",
    source: "curated",
    url: "https://www.dellscholars.org/",
    amount: 20000,
    deadline: "2026-12-01",
    eligibilityTags: ["undergraduate", "first-gen", "need-based", "high-school-senior"],
    requirements: ["essay", "transcript", "fafsa", "gpa-2.4-minimum"],
    estimatedEffort: 3,
    description: "Recognizes students who demonstrate grit and determination to succeed, with emphasis on those who have overcome significant obstacles.",
  },
  {
    id: "curated:007",
    title: "Ron Brown Scholar Program",
    source: "curated",
    url: "https://www.ronbrown.org/",
    amount: 40000,
    deadline: "2027-01-09",
    eligibilityTags: ["black", "high-school-senior", "undergraduate", "leadership"],
    requirements: ["essay", "transcript", "two-letters", "interview"],
    estimatedEffort: 5,
    description: "Provides $10,000 per year for four years to academically talented African American high school seniors. Includes mentoring and leadership development.",
  },
  {
    id: "curated:008",
    title: "Davidson Fellows Scholarship",
    source: "curated",
    url: "https://www.davidsongifted.org/gifted-programs/fellows-scholarship",
    amount: 50000,
    deadline: "2027-02-12",
    eligibilityTags: ["stem", "research", "undergraduate", "high-school-senior", "graduate"],
    requirements: ["essay", "research-portfolio", "two-letters", "project-summary"],
    estimatedEffort: 5,
    description: "For students 18 or younger who have completed a significant piece of work in STEM, literature, music, philosophy, or outside the box. Top awards $50,000.",
  },
  {
    id: "curated:009",
    title: "Burger King Scholars",
    source: "curated",
    url: "https://burgerkingscholars.com/",
    amount: 1000,
    deadline: "2026-12-15",
    eligibilityTags: ["undergraduate", "high-school-senior"],
    requirements: ["short-statement", "transcript"],
    estimatedEffort: 2,
    description: "Award for high school seniors planning to enroll in a two- or four-year college. Most awards $1,000; selected James W. McLamore awards up to $50,000.",
  },
  {
    id: "curated:010",
    title: "Goldwater Scholarship",
    source: "curated",
    url: "https://goldwaterscholarship.gov/",
    amount: 7500,
    deadline: "2027-01-27",
    eligibilityTags: ["stem", "research", "undergraduate", "sophomore", "junior", "merit-based"],
    requirements: ["essay", "research-essay", "three-letters", "transcript"],
    estimatedEffort: 5,
    description: "Premier undergraduate scholarship in natural sciences, mathematics, and engineering. For sophomores and juniors planning research careers.",
  },
  {
    id: "curated:011",
    title: "Truman Scholarship",
    source: "curated",
    url: "https://www.truman.gov/",
    amount: 30000,
    deadline: "2027-02-04",
    eligibilityTags: ["graduate", "junior", "leadership", "public-service"],
    requirements: ["essay", "policy-proposal", "four-letters", "interview", "transcript"],
    estimatedEffort: 5,
    description: "Graduate study award for college juniors committed to careers in government, nonprofits, or public service. Up to $30,000 toward graduate education.",
  },
  {
    id: "curated:012",
    title: "Udall Undergraduate Scholarship",
    source: "curated",
    url: "https://www.udall.gov/OurPrograms/Scholarship/Scholarship.aspx",
    amount: 7000,
    deadline: "2027-03-04",
    eligibilityTags: ["sophomore", "junior", "environment", "native-american", "undergraduate"],
    requirements: ["essay", "three-letters", "transcript"],
    estimatedEffort: 4,
    description: "For sophomores and juniors committed to careers related to environment or to Native American tribal policy and health care.",
  },
  {
    id: "curated:013",
    title: "Marshall Scholarship",
    source: "curated",
    url: "https://www.marshallscholarship.org/",
    amount: null,
    deadline: "2026-09-29",
    eligibilityTags: ["graduate", "international", "research", "merit-based"],
    requirements: ["essay", "personal-statement", "four-letters", "transcript", "interview"],
    estimatedEffort: 5,
    description: "Funds American students of high ability for two years of graduate study in any field at any UK university. All expenses paid.",
  },
  {
    id: "curated:014",
    title: "Rhodes Scholarship",
    source: "curated",
    url: "https://www.rhodesscholar.org/",
    amount: null,
    deadline: "2026-10-01",
    eligibilityTags: ["graduate", "international", "merit-based", "leadership"],
    requirements: ["essay", "personal-statement", "five-letters", "transcript", "interview"],
    estimatedEffort: 5,
    description: "World's oldest international scholarship, supporting two to three years of postgraduate study at the University of Oxford. Fully funded.",
  },
  {
    id: "curated:015",
    title: "Knight-Hennessy Scholars",
    source: "curated",
    url: "https://knight-hennessy.stanford.edu/",
    amount: null,
    deadline: "2026-10-08",
    eligibilityTags: ["graduate", "leadership", "merit-based"],
    requirements: ["essay", "two-letters", "transcript", "video-statement"],
    estimatedEffort: 5,
    description: "Fully-funded graduate fellowship at Stanford, including tuition, stipend, and travel. Develops a community of future leaders across disciplines.",
  },
  {
    id: "curated:016",
    title: "Horatio Alger National Scholarship",
    source: "curated",
    url: "https://scholars.horatioalger.org/scholarships/",
    amount: 25000,
    deadline: "2026-10-25",
    eligibilityTags: ["undergraduate", "high-school-senior", "need-based", "adversity"],
    requirements: ["essay", "transcript", "fafsa"],
    estimatedEffort: 3,
    description: "For high school seniors who have faced and overcome significant adversity, demonstrate critical financial need, and exhibit integrity and perseverance.",
  },
  {
    id: "curated:017",
    title: "Elks National Most Valuable Student",
    source: "curated",
    url: "https://www.elks.org/scholars/scholarships/mvs.cfm",
    amount: 50000,
    deadline: "2026-11-15",
    eligibilityTags: ["undergraduate", "high-school-senior", "leadership", "need-based", "merit-based"],
    requirements: ["essay", "transcript", "two-letters", "leadership-record"],
    estimatedEffort: 4,
    description: "Awards 500 four-year scholarships ranging from $4,000 to $50,000 based on scholarship, leadership, and financial need.",
  },
  {
    id: "curated:018",
    title: "AXA Achievement Scholarship",
    source: "curated",
    url: "https://us.axa.com/axa-foundation/axa-achievement-scholarship.html",
    amount: 25000,
    deadline: "2026-12-15",
    eligibilityTags: ["undergraduate", "high-school-senior", "merit-based", "leadership"],
    requirements: ["essay", "transcript"],
    estimatedEffort: 2,
    description: "Single-essay scholarship recognizing high school seniors who exemplify achievement in school, work, or community activities.",
  },
  {
    id: "curated:019",
    title: "Posse Foundation Scholarship",
    source: "curated",
    url: "https://www.possefoundation.org/",
    amount: null,
    deadline: "2026-08-22",
    eligibilityTags: ["undergraduate", "high-school-senior", "leadership", "merit-based"],
    requirements: ["nomination", "interview", "group-interview", "transcript"],
    estimatedEffort: 5,
    description: "Identifies, recruits, and trains high school students with extraordinary leadership potential to attend partner colleges in supportive 'Posses.' Full tuition.",
  },
  {
    id: "curated:020",
    title: "AAUW International Fellowships",
    source: "curated",
    url: "https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",
    amount: 50000,
    deadline: "2026-11-15",
    eligibilityTags: ["female", "graduate", "international", "research"],
    requirements: ["essay", "research-proposal", "three-letters", "transcript"],
    estimatedEffort: 5,
    description: "Supports women from countries other than the U.S. for full-time graduate or postdoctoral study in the United States.",
  },
  {
    id: "curated:021",
    title: "Society of Women Engineers Scholarship",
    source: "curated",
    url: "https://swe.org/scholarships/",
    amount: 15000,
    deadline: "2027-02-15",
    eligibilityTags: ["female", "stem", "engineering", "computer-science", "undergraduate", "graduate"],
    requirements: ["essay", "transcript", "two-letters"],
    estimatedEffort: 3,
    description: "SWE awards over $1M annually to women pursuing ABET-accredited engineering, computing, or technology degrees. Single application for many awards.",
  },
  {
    id: "curated:022",
    title: "AISES Intel Growing Educational Scholarship",
    source: "curated",
    url: "https://www.aises.org/scholarships",
    amount: 5000,
    deadline: "2026-05-31",
    eligibilityTags: ["native-american", "stem", "undergraduate", "graduate"],
    requirements: ["essay", "transcript", "tribal-affiliation-verification"],
    estimatedEffort: 3,
    description: "Supports Native American students pursuing STEM degrees, with emphasis on careers advancing Indigenous communities.",
  },
  {
    id: "curated:023",
    title: "McDonald's HACER National Scholarship",
    source: "curated",
    url: "https://www.mcdonalds.com/us/en-us/community/hacer.html",
    amount: 100000,
    deadline: "2027-02-06",
    eligibilityTags: ["hispanic", "undergraduate", "high-school-senior", "merit-based"],
    requirements: ["essay", "transcript", "two-letters"],
    estimatedEffort: 4,
    description: "Awards up to $100,000 over four years to outstanding Hispanic high school seniors. Among the largest Hispanic scholarship programs in the U.S.",
  },
  {
    id: "curated:024",
    title: "Discover Student Loans Scholarship Award",
    source: "curated",
    url: "https://www.discover.com/student-loans/scholarship/",
    amount: 5000,
    deadline: "2026-12-31",
    eligibilityTags: ["undergraduate", "high-school-senior", "merit-based"],
    requirements: ["form-only"],
    estimatedEffort: 1,
    description: "Random-draw scholarship for high school students, no essay required. Multiple awards each month leading up to the deadline.",
  },
  {
    id: "curated:025",
    title: "Tylenol Future Care Scholarship",
    source: "curated",
    url: "https://www.tylenol.com/news/subptyfcs",
    amount: 10000,
    deadline: "2026-10-15",
    eligibilityTags: ["healthcare", "graduate", "undergraduate", "nursing", "medicine"],
    requirements: ["essay", "transcript"],
    estimatedEffort: 2,
    description: "Supports students pursuing careers in healthcare-related fields including medicine, nursing, pharmacy, and public health.",
  },
  {
    id: "curated:026",
    title: "DAR Good Citizen Scholarship",
    source: "curated",
    url: "https://www.dar.org/national-society/scholarships",
    amount: 5000,
    deadline: "2027-01-31",
    eligibilityTags: ["undergraduate", "high-school-senior", "merit-based", "leadership"],
    requirements: ["essay", "transcript", "good-citizen-test"],
    estimatedEffort: 3,
    description: "Recognizes high school seniors who demonstrate dependability, service, leadership, and patriotism. Open to all U.S. high school seniors.",
  },
  {
    id: "curated:027",
    title: "AICPA Legacy Scholarship",
    source: "curated",
    url: "https://www.aicpa-cima.com/aicpa-foundation/aicpa-legacy-scholarships",
    amount: 10000,
    deadline: "2027-03-15",
    eligibilityTags: ["undergraduate", "graduate", "accounting", "business"],
    requirements: ["essay", "transcript", "two-letters", "aicpa-membership"],
    estimatedEffort: 3,
    description: "For accounting majors at U.S. institutions pursuing CPA-eligible programs. AICPA student affiliate membership required.",
  },
  {
    id: "curated:028",
    title: "Rotary Global Grant Scholarship",
    source: "curated",
    url: "https://www.rotary.org/en/our-programs/scholarships",
    amount: null,
    deadline: null,
    eligibilityTags: ["graduate", "international", "research", "public-service"],
    requirements: ["essay", "club-sponsorship", "interview", "research-plan"],
    estimatedEffort: 5,
    description: "Funds graduate study or research aligned with Rotary's areas of focus. Rolling sponsorship through local Rotary clubs; minimum $30,000 grant typical.",
  },
  {
    id: "curated:029",
    title: "National Merit Scholarship",
    source: "curated",
    url: "https://www.nationalmerit.org/",
    amount: 2500,
    deadline: "2026-10-01",
    eligibilityTags: ["undergraduate", "high-school-senior", "merit-based"],
    requirements: ["psat", "essay", "transcript"],
    estimatedEffort: 2,
    description: "Awarded based on PSAT/NMSQT performance to ~7,500 high school seniors annually. $2,500 single-payment National Merit awards plus corporate/college sponsored awards.",
  },
  {
    id: "curated:030",
    title: "ABC News Disney VoicesAmplified Scholarship",
    source: "curated",
    url: "https://www.disney.com/scholarships",
    amount: 10000,
    deadline: "2026-11-30",
    eligibilityTags: ["hispanic", "undergraduate", "journalism", "media", "minority"],
    requirements: ["essay", "media-portfolio", "transcript", "one-letter"],
    estimatedEffort: 4,
    description: "Supports underrepresented students pursuing careers in journalism, media production, and broadcasting. Internship opportunity included.",
  },
];
